export enum ESpecialButton {
  ALT = `{alt}`,
  ALT_LEFT = `{altleft}`,
  ALT_RIGHT = `{altright}`,
  BACKSPACE = `{bksp}`,
  CAPS = `{caps}`,
  CTRL = `{ctrl}`,
  CTRL_LEFT = `{ctrlleft}`,
  CTRL_RIGHT = `{ctrlright}`,
  ENTER = `{enter}`,
  SHIFT = `{shift}`,
  SHIFT_LEFT = `{shiftleft}`,
  SHIFT_RIGHT = `{shiftright}`,
  SPACE = `{space}`,
  TAB = `{tab}`,
}
